# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:51
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_photo_image_path, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись'),
        ),
    ]
