# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, verbose_name='О курсе'),
        ),
    ]
