# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Отоброжаемый текс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, verbose_name='Описание курса '),
        ),
    ]
