# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_code', '0003_auto_20170108_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_code.Course', verbose_name='Относиться к курсу'),
            preserve_default=False,
        ),
    ]
