# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_code', '0003_auto_20161120_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='curse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_code.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_code.Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='curse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_code.Course'),
            preserve_default=False,
        ),
    ]
