# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0003_auto_20161121_1224'),
        ('testing_code', '0004_auto_20161120_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='curse',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
