# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_code', '0005_auto_20161121_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='curse',
        ),
    ]
