# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_code', '0006_remove_answer_curse'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing_code.Course'),
            preserve_default=False,
        ),
    ]
