# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('title', models.CharField(help_text='О нас', max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ответ правильный')),
                ('position', models.TextField(blank=True, default=None, null=True, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(verbose_name='Отображение в UrL')),
                ('about', models.TextField(blank=True, verbose_name='Описание курса ')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField(verbose_name='Вопрос')),
                ('position', models.TextField(blank=True, default=None, null=True, verbose_name='Позиция')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question', verbose_name='Относиться к вопросу'),
        ),
    ]
