# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='position',
            field=models.TextField(blank=True, verbose_name='Позиция'),
        ),
    ]
