# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.TextField(blank=True, default=1, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
