# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_remove_aboutpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя'),
        ),
    ]
